### ISSUE TITLE
Example code message throws catastrophic

### ISSUE THREAD

**Issue by jreina** [PieceMaker/rminions#19]
Using the example R code, I am getting the following error:
```
simpleError in as.character(function (p, mean = 0, sd = 1, lower.tail = TRUE,     log.p = FALSE) .Call(C_qnorm, p, mean, sd, lower.tail, log.p)): cannot coerce type 'closure' to vector of type 'character'
```

This is with 8 workers and a Redis server running on Docker in a user-defined bridge network.

**Comment by PieceMaker** [comment]
This is actually a two-part error. First, the parameter `q` should actually be `p` in the example. I have fixed this. However, a catastrophic error is thrown which means the error handling in `minionWorker` is not working as expected and needs to be re-evaluated. I am going to leave this issue open for now.

Thanks for the issue!
